### ISSUE TITLE
Emerson_said.github.io

### ISSUE THREAD

**Issue by Emerosnsaidbkajs** [pereirajs/pagina#100]
Subiendo archivos a mi página

**Comment by h3ct0rjs** [comment]
@Emerosnsaidbkajs ??

**Comment by jonalvarezz** [comment]
Hola @Emerosnsaidbkajs, marcaremos el issue como inválido. Si piensas que es un error puedes reabrirlo – Y si necesitas apoyo con algo quedamos atentos en el grupo de Telegram o WhatsApp.
