### ISSUE TITLE
Quitar la cinta "Fork me on github"

### ISSUE THREAD

**Issue by cronopio** [pereirajs/pagina#18]
Cambiemos esa cinta o de posicion o de lugar o de forma, quiza como un boton o algo mas podria funcionar mejor.

Por ahora no esta siendo muy usado el boton y fuera de eso cuando la pantalla es pequeña se sobre pone con los botones del menu superior.

**Comment by epatarroyo** [comment]
Se puede poner un boton en la zona arriba del formulario de contacto donde actualmente salen unas imagenes rotas

**Comment by cronopio** [comment]
Si de acuerdo. Un boton al repo y otro boton al chat! Gracias @epatarroyo
