### ISSUE TITLE
Migracion Hosting

### ISSUE THREAD

**Issue by cronopio** [pereirajs/pagina#26]
Dentro de los proximos meses Nodejitsu dejara de proveer el servidor para alojar la pagina, por ahora una alternativa que se me ocurre es usar Github Pages. Entonces hay que hacer el plan de migracion y ejecutarlo.

Alguna otra idea?

**Comment by pin3da** [comment]
A mí me parece que gh-pages está muy bien por ahora (: lo importante es no perder el pereirajs.org.

**Comment by jonalvarezz** [comment]
También me parece bien con Github Pages. Perderíamos alguna cosa por no tener un server propio?

**Comment by cronopio** [comment]
No nada, al parecer gh-pages soporta el dominio sin problemas

**Comment by epatarroyo** [comment]
y tiene algun costo?


Ernesto Patarroyo
+57 310 259 3777
http://openweb.co

**Comment by cronopio** [comment]
No, ningun costo, es un servicio gratuito que todos los repos de Github tienen.

**Comment by jonalvarezz** [comment]
Si, soporta custom domains, desde que no necesitemos nada por fuera de contenido estático, pienso que está bien. ¿O le parece necesario un server propio?

**Comment by cronopio** [comment]
Todo el codigo aun es solo front-end, no hacemos nada de backed.

**Comment by epatarroyo** [comment]
Sirve cualquier servidor?

Yo puedo donar un espacio de 1gb.

**Comment by ogranada** [comment]
Para el envio de formularios o correos podriamos necesitar backend, pero por ahora no es necesario.

**Comment by cronopio** [comment]
@epatarroyo Muchas gracias por el ofrecimiento. La idea es que a futuro si necesitaremos un servidor para hacer cosas de back-end, basicamente seria un linux con accesso shell como root. Digital Ocean es una excelente alternativa. 
Por ahora como no hacemos nada de back-end el servicio gratuito de Github Pages es una muy buena alternativa.

**Comment by jonalvarezz** [comment]
Que sea GH entonces

**Comment by cronopio** [comment]
Ya se desplego como prueba en los servidores de Github:

## 192.30.252.153
## 192.30.252.154

Para poder hacerlos funcionar tienen que hacer la peticion usando el dominio de pereirajs, lo que se puede hacer para probar entonces es agregar esas lineas al `/etc/hosts`

```
192.30.252.153 pereirajs.org pereirajs.org
192.30.252.154 pereirajs.org pereirajs.org
```

desde la consola y como root seria algo como:

```bash
$ echo "192.30.252.153 pereirajs.org pereirajs.org" >> /etc/hosts
$ echo "192.30.252.154 pereirajs.org pereirajs.org" >> /etc/hosts
```

**Comment by pin3da** [comment]
Ya los probé y funcionaron muy bien. Por allá me salió un error de CORS pero creo que es del google analytics. :+1:

**Comment by cronopio** [comment]
@pin3da No deberia dar error de nada.

Porfa verifique que fue y saque logs o screenshots.

:+1:

**Comment by pin3da** [comment]
@cronopio este es el error: 

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.google.com/ServiceLogin?service=mymaps&passive=1209600&continue=https://www.google.com/maps/d/gen204?a%3D58%26width%3D0%26height%3D0%26s%3D7&followup=https://www.google.com/maps/d/gen204?a%3D58%26width%3D0%26height%3D0%26s%3D7. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by cronopio** [comment]
mmmm..... es el mapa??
Siempre he querido como poner una imagen, en vez de ese gmap. Sera que ponemos esa imagen que publicaron los del vivelab?

![mapa-vivelab](https://pbs.twimg.com/media/Bx2WpkxCMAEa2Zv.jpg:large)

**Comment by pin3da** [comment]
A mí me parece bien la imagen. ¿ Qué dicen los demás ?

**Comment by jonalvarezz** [comment]
Not bad. Imagen con link a GMaps

**Comment by cronopio** [comment]
Bueno ya cambie todo y desplegue en ese de pruebas.

Cuando cambie los DNS será produccion.

Hay que hacer mas pruebas para hacer el cambio este domingo

**Comment by cronopio** [comment]
Ya cambie los DNS :computer: ya estamos oficialmente en GH Pages

**Comment by jhonber** [comment]
:+1:

**Comment by pin3da** [comment]
Bien por la migracion ! :+1:
