### ISSUE TITLE
Nuevo diseño para el sitio

### ISSUE THREAD

**Issue by jonalvarezz** [pereirajs/pagina#45]
Estoy trabajando en darle un nuevo diseño al sitio para mantenerlo más fresco.

[Vista previa](https://cloud.githubusercontent.com/assets/2167222/15711652/8eac7840-27d4-11e6-83ec-35f02e1e490e.jpg)
[Último update](https://cloud.githubusercontent.com/assets/2167222/17834900/e8060ce6-671a-11e6-9814-11cf65fb64d6.jpg)

Estas son las razones por lo que lo hice. Espero escuchar sus comentarios y sugerencias.
## Algunos problemas del diseño actual
1. **No hay llamado a la acción claro cuando se carga el sitio**. Hay un menú de color rojo de Próxima reunión, pero por el copy y el color, que no es muy legible, no se podría considerar como llamado de acción (CTA)
2. **Registrarse o inscribirse requiere al menos dos iteraciones**: 1. Realizar scroll a la siguiente sección o Click en Próxima Reunión; 2. Click en suscribir.
3. **Hay textos que pueden ser omitidos o mejorados**: Por ejemplo Objetivos, no debería ser algo primario del sitio y por lo regular nadie lee esas cosas.
4. **Problemas de responsive**, el menú en especial no se comporta bien entre 767 y 1200px.
## Solución

Orientar el diseño hacia el registro/inscripción a una reunión.
## Justificación del nuevo diseño.

([Ver diseño](https://cloud.githubusercontent.com/assets/2167222/15711652/8eac7840-27d4-11e6-83ec-35f02e1e490e.jpg))
1. Enfocar el sitio a registrar/suscribir los visitantes. Lo primero que aparece en el sitio serán llamados de acción para inscribirse a la reunión actual y en caso que no haya reunión, un botón directo para suscribirse y no perder la próxima reunión. El siguiente tema en orden de importancia o flujo del diseño serían patrocinadores, seguido por Charlas y por último información sobre PerJS.
2. Reducir las opciones del menú y dejar sólo las de interés para un visitante recurrente/nuevo.
3. Reducir la cantidad de texto y contar lo que hacemos de manera más informal y pasar esta información a un segundo plano.

**Comment by pin3da** [comment]
- Totalmente de acuerdo con enfocar el sitio a registrar/suscribir visitantes.
- Lo de los objetivos me parece importante dejarlo, así sea más abajo, pero que esté disponible para los visitantes que les interese.

Tengo una duda con la sección de charlas, como funciona actualmente la lista crece y crece, luego uno resulta dando scroll un rato sólo para ver qué hay debajo ¿cómo podemos mejorar esto, será que las agrupamos y sólo mostramos imágenes de las más recientes ?

Y lo más importante, ¡ gracias por la iniciativa !

**Comment by jonalvarezz** [comment]
@pin3da Muy buen el que resalta de las charlas. Por ahora sólo hice esas dos primeras partes, las que muestro en la imagen. La idea es saber si les parece bien como va para continuar con las otras secciones.

**Comment by cronopio** [comment]
love it
Me encanta

**Comment by jonalvarezz** [comment]
Genial, seguiré avanzando entonces para crear el preview de patrocinadores y charlas. Seguiré actualizando este mismo Issue. Thanks for the support

**Comment by jonalvarezz** [comment]
Update: [Preview](https://cloud.githubusercontent.com/assets/2167222/16275966/11ef646c-3872-11e6-96aa-c3da77e7b46f.jpg)

- Reduce clicks para inscripción a 0 clicks *
- Muestra el lugar de la reunión
- Agrega sección de patrocinadores
- Cambia el font

* Este punto implica integrar el form con algún servicio, pienso en integrarlo con los formularios de MailChimp directamente y no utilizar Google Forms. Sería crear lista en MailChimp por cada evento, que no es diferente a lo que hacemos con Google Forms. Qué opinan de esto?

**Comment by cronopio** [comment]
Me suena la idea, exploremos bien esas opciones que nos da MailChimp y dejamos de usar GForms

**Comment by jonalvarezz** [comment]
Update: [Preview](https://cloud.githubusercontent.com/assets/2167222/17834900/e8060ce6-671a-11e6-9814-11cf65fb64d6.jpg) 🎉

* Incluye las secciones restantes de eventos, colaboradores y contáctenos.
* Cambia el orden de las secciones para darle más importancia a lo que hacemos y posteriormente al cómo (patrocinadores, colaboradores).

**Nota sobre los eventos:** Inicialmente sólo aparecen las fotos, al poner el mouse sobre una de las fotos o al presionar touch en un dispositivo móvil, aparecerá el título del evento como se muestra en el segundo evento. Sólo se cargan los 5 últimos eventos y se incluye un enlace de Ver todo para desplegar los demás eventos.

**Comment by pin3da** [comment]
:heart_eyes: Esta re cool ! :tada:

**Comment by cronopio** [comment]
Esta super chevere, al fin los objetivos donde sera que los ponemos? Tambien es importante que todos tengamos la misma información sobre el porque y para que de la comunidad.

PD: Tambien deberiamos repasar los objetivos mismos, pero eso sera en otro issue

Vamos estando ready para hacer merge

**Comment by jonalvarezz** [comment]
@cronopio @pin3da realmente consideran necesario poner los objetivos?  A mi eso me suena a año 2009, y en caso de ponerlos los ubicaría en un lugar secundario.

No tengo código aún, pero si les parece puedo proponer este fin de semana una estructura básica y clara para empezar luego desde ahí.

Para esa estructura tengo tres posiciones que quiero concertar:

1. Crear una estructura muy básica, más o menos como la de la página actual que no requiera muchos conocimientos avanzados. **Desventaja**: Limita el uso de otras herramientas para automatizar cosas como deploy, compresión de assets, linters, demás.

2. Utilizar una estructura más *moderna* con herramientas y scripts listos para compilar, comprimir, correr en dev, deploy. **Desventaja**: Si hay colaboradores requieren más conocimiento para aportar a la página.

3. Utilizar un generador estático de sitios. **Desventaja**: Requerimientos para aportar. **Ventaja**: Mantenimiento, automatización, facilidad de publicaciones periódicas, flexibilidad para crear páginas. Mi sitio personal lo hice con Wintersmith y me gustó mucho. Pueden ver la estructura [aquí](https://github.com/jonalvarezz/site)

**Comment by pin3da** [comment]
- __Objetivos:__ yo creo que si planteamos unos objetivos más cortos podríamos ponerlos en la sección "Nosotros" y así no es necesario crear más secciones. Creo que hay 2 cosas fundamentales que no podemos olvidar como objetivos: *Crear comunidad en pereira*  y que es un *espacio libre donde cualquiera es bienvenido*.

- __Estructura:__ Podemos hacer una mezcla entre 1 y 2, es decir, automatizar lo que se pueda automatizar, pero que cuando alguien nuevo llegue pueda escribir contenido fácilmente. Algo como
`npm run serve` para desarollar local, y que cuando haga push a un branch específico se haga deploy automáticamente.

**Comment by pin3da** [comment]
@cronopio @jonalvarezz any update ? Deberíamos aprovechar el año nuevo para cambiar el website.

PS: creo que ya ha pasado suficiente tiempo para que actualicemos la lista de patrocinadores y colaboradores. ¿ qué opinan ?

**Comment by jonalvarezz** [comment]
Agree y agree.

Aún no creo el scaffolding pero ya tengo una idea de cómo hacerlo para
incorporar algunas herramientas y mantenerlo simple o típico para alguien
que apenas empieza.

2017-01-03 15:09 GMT-05:00 Manuel Pineda <notifications@github.com>:
