### ISSUE TITLE
Datos de Colaboradores

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#75]
> Depende de #76 

Definir cómo se almacenarán y consultarán los datos de __Colaboradores__

**Comment by h3ct0rjs** [comment]
Saludos, 
Es posible construir un archivo json para esta propuesta, la imagen que se muestre en el sitio podria ser tomada de gravatar. Creo que el sitio anterior tenia algo parecido, además será fácil actualizarlo con los datos de cada integrante mediante pull request.
