### ISSUE TITLE
Configuración de Almacenamiento

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#76]
Considerando que es una web estática:

Definir cuál va a ser el modo de almacenamiento y consulta de datos en general (Definir tecnologías o medios)

**Comment by arodrigueze0215** [comment]
Hola @arendondiosa Considero que para el almacenamiento de eventos, podemos tomarlos desde el sitio de Pereira Tech Talk con la api que allí se expone. De esta manera no tendríamos que pensar en un mecanismo de almacenamiento. Que dice?

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
