### ISSUE TITLE
Datos Patrocinadores

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#77]
> Depende de #76 

Definir cómo se almacenarán y consultarán los datos de __Patrocinadores__

**Comment by arodrigueze0215** [comment]
La manera como lo manejamos es similar como los Colaboradores, se crea un archivo JSON donde tiene toda la data de los patrocinadores, si se quiere modificar o adicionar un patrocinador más, debe ser por medio de un Pull request.
Las imagenes se manejan como archivos estaticos.
