### ISSUE TITLE
Menú

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#80]
![image](https://user-images.githubusercontent.com/14989202/45574737-99084180-b836-11e8-9390-c1c91dd537b6.png)

Agregar estilo al menú y las diferentes urls

> Depende de #71 y #79

**Comment by arodrigueze0215** [comment]
Hace falta que la barra del menú se fije cuando se hace scroll.

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
