### ISSUE TITLE
Sección de Contacto

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#81]
> Depende de #70

![image](https://user-images.githubusercontent.com/14989202/45574910-20ee4b80-b837-11e8-83c4-9309b781214f.png)

- Debe pertenecer al layout 
- Dar estilo al formulario

> Depende de #78 #82

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
