### ISSUE TITLE
Sección Redes

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#83]
> Depende de #70

![image](https://user-images.githubusercontent.com/14989202/45575011-935f2b80-b837-11e8-81f5-afd798d44f0b.png)

- Debe ir en el layout
- Agregar estilo y redes sociales actuales

> Depende de #71

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
