### ISSUE TITLE
Sección Patrocinadores

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#84]
> Depende de #70

![image](https://user-images.githubusercontent.com/14989202/45575124-05d00b80-b838-11e8-8744-e9c2f8fb04c6.png)

- Agregar Estilo
- Agregar patrocinadores dependiendo de #77 (Si no hay, mostrar un alternativo)
- Agregar opción para ser patrocinador (Funcionalidad en otro issue)

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
