### ISSUE TITLE
Sección Colaboradores

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#85]
> Depende de #70

![image](https://user-images.githubusercontent.com/14989202/45575285-9575ba00-b838-11e8-94cf-ed84bc79cae0.png)

- Agregar estilo a la sección
- Agregar colaboradores dependiendo de #75 (O alternativa si no hay datos)

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
