### ISSUE TITLE
Sección sobre Nosotros

### ISSUE THREAD

**Issue by arendondiosa** [pereirajs/pagina#86]
> Depende de #70 

![image](https://user-images.githubusercontent.com/14989202/45575489-5300ad00-b839-11e8-8195-badfe729461a.png)

- Agregar estilo e información
- Agregar botón para postular charla (Se define funcionalidad en otro issue)

**Comment by santiaguf** [comment]
Closing this because the website has been inactive for a few years. If we reopen the Community/Website, please open a new issue.
